// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQTPNE0N_eYjoIU0fVfoLoyBk3nCvBhxo',
    appId: '1:808833400555:web:ab31a624b1e5776f4748ae',
    messagingSenderId: '808833400555',
    projectId: 'yemektarifi-fad39',
    authDomain: 'yemektarifi-fad39.firebaseapp.com',
    storageBucket: 'yemektarifi-fad39.appspot.com',
    measurementId: 'G-2S4N91SGJT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvJ9cnD4vt8kGAl8DQ3H8eVEnly6jZ8hc',
    appId: '1:808833400555:android:6e01c050f2b09db04748ae',
    messagingSenderId: '808833400555',
    projectId: 'yemektarifi-fad39',
    storageBucket: 'yemektarifi-fad39.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIQaFwUCNUj3ZeE6LqLjJW02HR8fxcMdk',
    appId: '1:808833400555:ios:8dc68d75d035e65c4748ae',
    messagingSenderId: '808833400555',
    projectId: 'yemektarifi-fad39',
    storageBucket: 'yemektarifi-fad39.appspot.com',
    iosClientId: '808833400555-m02lgh8o11n5p0vbeq8j0e53oh7rfrgb.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterYemekTarifi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIQaFwUCNUj3ZeE6LqLjJW02HR8fxcMdk',
    appId: '1:808833400555:ios:8dc68d75d035e65c4748ae',
    messagingSenderId: '808833400555',
    projectId: 'yemektarifi-fad39',
    storageBucket: 'yemektarifi-fad39.appspot.com',
    iosClientId: '808833400555-m02lgh8o11n5p0vbeq8j0e53oh7rfrgb.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterYemekTarifi',
  );
}
