// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB29PS6sXlO3pClbARom7vjfXTg5a56dgo',
    appId: '1:622096366862:web:3cbea328dece102f7ceb5f',
    messagingSenderId: '622096366862',
    projectId: 'yemek-tarifi-flutter',
    authDomain: 'yemek-tarifi-flutter.firebaseapp.com',
    storageBucket: 'yemek-tarifi-flutter.appspot.com',
    measurementId: 'G-6C28ZGB32B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe6bLjYhNqE-ljq_kr3CwkA8BilK02ZS0',
    appId: '1:622096366862:android:7cfe4783aa40e4e17ceb5f',
    messagingSenderId: '622096366862',
    projectId: 'yemek-tarifi-flutter',
    storageBucket: 'yemek-tarifi-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIkf2v9id_4rJzwS47C_s3fXuXUBYKmJg',
    appId: '1:622096366862:ios:118393dbdc41b95c7ceb5f',
    messagingSenderId: '622096366862',
    projectId: 'yemek-tarifi-flutter',
    storageBucket: 'yemek-tarifi-flutter.appspot.com',
    iosClientId: '622096366862-tijebtc1m7jf4pjd5hrorodf14g0ikhk.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterYemekTarifi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIkf2v9id_4rJzwS47C_s3fXuXUBYKmJg',
    appId: '1:622096366862:ios:118393dbdc41b95c7ceb5f',
    messagingSenderId: '622096366862',
    projectId: 'yemek-tarifi-flutter',
    storageBucket: 'yemek-tarifi-flutter.appspot.com',
    iosClientId: '622096366862-tijebtc1m7jf4pjd5hrorodf14g0ikhk.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterYemekTarifi',
  );
}
